### PR TITLE
Return verified state

### PR DESCRIPTION
**Pull request by dharshann**

### CODE REVIEW

**Comment by harman28** [comment]
Thanks for the pull request @dharshann!

I'm not sure about this code change though. If you're calling `verify_payment_signature` method, you're expecting it to throw an exception if the hash doesn't match. So if the method is returning anything at all in this PR, it will always return true. So why is this required?

**Comment by harman28** [comment]
@dharshann As per discussion on #73, we'll like to get this merged. The build step is failing at the moment, could you get that fixed?

**Comment by dharshann** [comment]
@harman28  Haven't worked with travis build process. Will check and update.

**Comment by harman28** [comment]
Rubygems no longer supports Ruby v2.2, so gem update is failing. We fixed this in master recently, so just rebasing your branch over master should fix it.

**Pull request merged**
