### PR TITLE
Update request.rb

### PR DESCRIPTION
**Pull request by erprincebansal**
I have debugged the code and found that httparty response.parsed_response is returning a json string object. so wee need to parse it as json object. raise_error(response['error'], res.code) if response.key?('error') this line is producing error (NoMethodError for key? on String). So we need to update the above code.

### CODE REVIEW

**Comment by captn3m0** [comment]
Could you check which ruby version are you on? The [`parsed_response`](http://www.rubydoc.info/github/jnunemaker/httparty/HTTParty%2FResponse%3Aparsed_response) method should be returning a hash.

Also, all the tests are failing because JSON.parse expects a string, but you are passing it a Hash.

I might be able to better help if you could give me a snippet of how you are using the library.

**Comment by priyank-gupta** [comment]
@captn3m0 +1
Using ruby 2.1.0

**Comment by captn3m0** [comment]
Thanks for the update. We have isolated the issue as part of a recent regression, and are fixing it. I'll update here once the fix is deployed.

**Comment by captn3m0** [comment]
This is now fixed. The API should now be returning a content-type of `application/json` which would make sure that HTTPParty parses the response properly.

Thanks for the PR :+1:

**Pull request closed without merging**
