### PR TITLE
Delete Addon request returns empty array and not entity

### PR DESCRIPTION
**Pull request by pikender**
**Note**: It's a separate PR for easy discussion but ideally is part of  #48 

Api Response is assumed to have `entity`key which can be translated to a Razorpay::Entity, but delete_addon api _response returns empty array_ `[]` .
**Hence, mocking expectation by mutating response `[]` to have entity key `{ 'entity' => 'Void' } `** for minimal changes

**Request/Response**

```
2.3.3 :004 > s = Razorpay::Addon.delete('ao_97jOo24R9eB7lJ')
opening connection to api.razorpay.com:443...
opened
starting SSL for api.razorpay.com:443...
SSL established
<- "DELETE /v1/addons/ao_97jOo24R9eB7lJ HTTP/1.1\r\nContent-Type: application/json\r\nAccept: application/json\r\nUser-Agent: Razorpay-Ruby/2.1.0.pre\r\nAuthorization: Basic xxxxx\r\nConnection: close\r\nHost: api.razorpay.com\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Cache-Control: max-age=0, must-revalidate, no-store, nocache, private\r\n"
-> "Content-Type: application/json\r\n"
-> "Date: Thu, 30 Nov 2017 15:41:14 GMT\r\n"
-> "Expires: Fri, 01 Jan 1990 00:00:00 GMT\r\n"
-> "Pragma: no-cache\r\n"
-> "Server: Apache\r\n"
-> "Strict-Transport-Security: max-age=63072000; includeSubDomains\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "Content-Length: 2\r\n"
-> "Connection: Close\r\n"
-> "\r\n"
reading 2 bytes...
-> "[]"
read 2 bytes
Conn close
 => #<Razorpay::Entity:0x000000048233a0 @attributes={}>
```

### CODE REVIEW

**Comment by harman28** [comment]
This looks like an issue with the delete_addon API, rather than this SDK. Thanks for your report, I'll get the API fixed.

**Comment by pikender** [comment]
@harman28 I have opened an issue #50  which needs discussion regarding another special api behaviour. Can you please have a look at it too. **SDK is well-written and api is carved out well, embracing consistency and simplicity. Hats off to Razorpay Team :100:** Smoothing up of #49 and #50 will help maintain the same.

**Comment by captn3m0** [comment]
Thanks a lot for the PRs. We won't be merging this, since we are looking to standardize all delete routes internally. Most probably returning 204s, but this is still under consideration.

Meanwhile, you can use raw request as a workaround.

**Comment by pikender** [comment]
Thanks @captn3m0 for the feedback. It was surely a workaround as per current implementation so no surprise at the decision of no-merge :+1: 

Looking forward to the final decision on _delete response_ standardisation.

There is no activity on the other PR #48 . Can you please share whether there is any missing requisite for the merge consideration ?

**Comment by captn3m0** [comment]
@pikender We're looking at #48, expect it to get merged soon. @harman28 had a few minor suggestions that I want to run through first.

**Comment by pikender** [comment]
:cool: will wait for the feedback :blush:

**Pull request closed without merging**
